//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell_Stock
    {
        public int id { get; set; }
        public int product_quantity { get; set; }
        public Nullable<System.DateTime> selling_date { get; set; }
        public int buying_rate { get; set; }
        public int selling_rate { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> supplierid { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
